// Initial library supplied by the user. Saved libraries, including an empty one, take precedence.
export const PRESET_ROOTS = [
  ["Translator", "翻译器", "Google Translator、Online Translator"],
  ["Generator", "生成器", "Password Generator、QR Code Generator"],
  ["Example", "示例", "Code Example、Resume Example"],
  ["Convert", "转换", "PDF to Word、Currency Convert"],
  ["Online", "在线", "Online Shopping、Online Learning"],
  ["Downloader", "下载器", "YouTube Downloader、MP3 Downloader"],
  ["Maker", "制作器", "Logo Maker、Video Maker"],
  ["Creator", "创作者", "Content Creator、Logo Creator"],
  ["Editor", "编辑器", "Photo Editor、Video Editor"],
  ["Processor", "处理器", "Data Processor、Image Processor"],
  ["Designer", "设计师", "Graphic Designer、Web Designer"],
  ["Compiler", "编译器", "C++ Compiler、Java Compiler"],
  ["Analyzer", "分析器", "Data Analyzer、Text Analyzer"],
  ["Evaluator", "评估器", "Product Evaluator、Website Evaluator"],
  ["Sender", "发件人", "Email Sender"],
  ["Receiver", "收件人", "Bluetooth Receiver"],
  ["Interpreter", "解释器", "Python Interpreter、PHP Interpreter"],
  ["Uploader", "上传器", "File Uploader、Image Uploader"],
  ["Calculator", "计算器", "Online Calculator、Mortgage Calculator"],
  ["Sample", "样本", "Resume Sample"],
  ["Template", "模板", "Website Template"],
  ["Format", "格式", "Text Format、Image Format"],
  ["Builder", "构建器", "App Builder、Website Builder"],
  ["Scheme", "方案", "Business Scheme"],
  ["Pattern", "模式", "Knitting Pattern"],
  ["Checker", "检查器", "Grammar Checker"],
  ["Detector", "检测器", "Plagiarism Checker"],
  ["Scraper", "爬虫", "Web Scraper、Email Scraper"],
  ["Manager", "管理器", "Project Manager、Task Manager"],
  ["Explorer", "浏览器", "File Explorer、Web Explorer"],
  ["Dashboard", "仪表盘", "Data Dashboard、Project Dashboard"],
  ["Planner", "计划器", "Event Planner、Trip Planner"],
  ["Tracker", "追踪器", "Package Tracker、Fitness Tracker"],
  ["Recorder", "录制器", "Audio Recorder、Screen Recorder"],
  ["Optimizer", "优化器", "PC Optimizer、SEO Optimizer"],
  ["Scheduler", "调度器", "Meeting Scheduler、Flight Scheduler"],
  ["Converter", "转换器", "Currency Converter、PDF Converter"],
  ["Viewer", "查看器", "PDF Viewer、Image Viewer"],
  ["Extractor", "提取器", "Text Extractor、Audio Extractor"],
  ["Monitor", "监视器", "System Monitor、Network Monitor"],
  ["Notifier", "通知器", "Email Notifier、News Notifier"],
  ["Verifier", "验证器", "Identity Verifier、Data Verifier"],
  ["Simulator", "模拟器", "Flight Simulator、Game Simulator"],
  ["Assistant", "助手", "Virtual Assistant、AI Assistant"],
  ["Constructor", "构建者", "Website Constructor、Building Constructor"],
  ["Comparator", "比较器", "Price Comparator、Product Comparator"],
  ["Navigator", "导航器", "GPS Navigator、Map Navigator"],
  ["Syncer", "同步器", "Phone Syncer、Cloud Syncer"],
  ["Connector", "连接器", "USB Connector、Power Connector"],
  ["Cataloger", "目录制作人", "Library Cataloger、Digital Asset Cataloger"],
  ["Responder", "响应器", "Emergency Responder、Automated Responder"],
].map(([root, meaning, examples]) => ({ root, meaning, examples }));
